language: node_js
node_js:
- '12.22.10'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/malentille.git"
  - secure: SMzSr7nKgWJC8ldpTbXmsRHhH55GLYeg+CNQrkE3c5t17dZMz47GBsx5N+TGnAKkTu/NBiEO619b71GZUgbsz0Nxid2iAyV3icraae3K+a7Hhr7oyFVZE+RyGrS3YDV5P4C3oEyYex1OW1OQvz/TIeaeBuczPfZ+ADKYy5m59hpk6Ra/Ch+/G5cVJoT+3av5LmGiuH3cipxy8L1Obl1YgfxrhrBFie8ZZiLexAJwvqCBU8tQco1mXdWr0XzykNEXhR9ZDiUzKt/zZAnL6Ptd+7IH93/DQDf5kXRO1eSjPp/6dhG5+tdcatMnwvSDTq2J8ZYAMeG4m82PX6RtMq6FC4MjxSBnLISslqgwhJXkM2HkfBWsaQsfvGp9y1yBFP4RNTGSoHejMQ/bnTWF6jnDH4I2GoU9mh0Fja0iFVARsudQMIJqVqawqv2jaNIiNfyxzqvpHzppnTj9qGefSFYBfBzIvIKJ1CWR5nGRwyUb6QN9nmG/EB7i08xD0ZyikC8WlNm6DpKafF3FoSXtM5ppQ7lEre/2dc15UF6VSr2PcaRrd+ouOGt067dgfGfWloq1gNh3w9jUvGxRauVwJdbHK3NpmaTR/nVTguz0Aws6JBNhZTg8oyxVzrvHUDhnCWTnc2jenGT8nyVn7JPyxfGiISEpV12b3zyUxsIwgvnomas=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - latest
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_eaa2ea2b97e9_key -iv $encrypted_eaa2ea2b97e9_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
